name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and push
      run: |
        echo "${{ secrets.DOCKERPW}}" | docker login -u "ashishsingh333" --password-stdin
        docker image build -t ashishsingh333/sttest:latest .
        docker push ashishsingh333/sttest:latest
